from .z3 import *
from .z3core import *
from .z3printer import *
from typing import Any

def Pi(ctx: Any | None = ...): ...
def E(ctx: Any | None = ...): ...
def MkInfinitesimal(name: str = ..., ctx: Any | None = ...): ...
def MkRoots(p, ctx: Any | None = ...): ...

class RCFNum:
    num: Any
    ctx: Any
    def __init__(self, num, ctx: Any | None = ...) -> None: ...
    def __del__(self) -> None: ...
    def ctx_ref(self): ...
    def compact_str(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __div__(self, other): ...
    def __rdiv__(self, other): ...
    def __neg__(self): ...
    def power(self, k): ...
    def __pow__(self, k): ...
    def decimal(self, prec: int = ...): ...
    def __lt__(self, other): ...
    def __rlt__(self, other): ...
    def __gt__(self, other): ...
    def __rgt__(self, other): ...
    def __le__(self, other): ...
    def __rle__(self, other): ...
    def __ge__(self, other): ...
    def __rge__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def split(self): ...
